#!/bin/sh
set -eu

CONFIG_PATH="/usr/share/nginx/html/runtime-config.js"
RELEASE_HEADER_INCLUDE="/etc/nginx/conf.d/release-header.inc"
UPSTREAM_RELEASE_VALUE="${UPSTREAM_RELEASE:-${IMAGE_TAG:-${HOSTNAME:-unknown}}}"

printf 'add_header X-Upstream-Release "%s" always;\n' "$UPSTREAM_RELEASE_VALUE" > "$RELEASE_HEADER_INCLUDE"

if [ -n "${VITE_UPSTREAM_API_URL:-}" ] || [ -n "${VITE_CKAN_URL:-}" ] || \
   [ -n "${VITE_TAPIS_BASE_URL:-}" ] || [ -n "${VITE_TAPIS_PODS_BASE_URL:-}" ] || \
   [ -n "${VITE_TAPIS_OAUTH_CLIENT_ID:-}" ] || [ -n "${VITE_TAPIS_OAUTH_CLIENT_KEY:-}" ]; then
  {
    echo 'window.__UPSTREAM_CONFIG__ = window.__UPSTREAM_CONFIG__ || {};'
    if [ -n "${VITE_UPSTREAM_API_URL:-}" ]; then
      echo "window.__UPSTREAM_CONFIG__.VITE_UPSTREAM_API_URL = \"${VITE_UPSTREAM_API_URL}\";"
    fi
    if [ -n "${VITE_CKAN_URL:-}" ]; then
      echo "window.__UPSTREAM_CONFIG__.VITE_CKAN_URL = \"${VITE_CKAN_URL}\";"
    fi
    if [ -n "${VITE_TAPIS_BASE_URL:-}" ]; then
      echo "window.__UPSTREAM_CONFIG__.VITE_TAPIS_BASE_URL = \"${VITE_TAPIS_BASE_URL}\";"
    fi
    if [ -n "${VITE_TAPIS_PODS_BASE_URL:-}" ]; then
      echo "window.__UPSTREAM_CONFIG__.VITE_TAPIS_PODS_BASE_URL = \"${VITE_TAPIS_PODS_BASE_URL}\";"
    fi
    if [ -n "${VITE_TAPIS_OAUTH_CLIENT_ID:-}" ]; then
      echo "window.__UPSTREAM_CONFIG__.VITE_TAPIS_OAUTH_CLIENT_ID = \"${VITE_TAPIS_OAUTH_CLIENT_ID}\";"
    fi
    if [ -n "${VITE_TAPIS_OAUTH_CLIENT_KEY:-}" ]; then
      echo "window.__UPSTREAM_CONFIG__.VITE_TAPIS_OAUTH_CLIENT_KEY = \"${VITE_TAPIS_OAUTH_CLIENT_KEY}\";"
    fi
  } > "$CONFIG_PATH"
fi

# Write nginx API proxy config when UPSTREAM_API_PROXY_URL is set.
# Requests to /api/ are forwarded server-side, avoiding browser CORS.
if [ -n "${UPSTREAM_API_PROXY_URL:-}" ]; then
  API_HOST=$(echo "$UPSTREAM_API_PROXY_URL" | sed 's|https\?://||' | sed 's|/.*||')
  cat > /etc/nginx/conf.d/api-proxy.inc << NGINXEOF
# Generated by docker-entrypoint.sh — do not edit manually.
resolver 8.8.8.8 1.1.1.1 valid=30s ipv6=off;
location /api/ {
    set \$api_upstream "${UPSTREAM_API_PROXY_URL}";
    proxy_pass \$api_upstream;
    proxy_ssl_server_name on;
    proxy_set_header Host ${API_HOST};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_http_version 1.1;
    proxy_read_timeout 300s;
    proxy_connect_timeout 60s;
}
NGINXEOF
fi

# Always write a Tapis proxy so instance discovery works without CORS errors.
# Browser calls /tapis-proxy/v3/pods → nginx forwards to portals.tapis.io.
TAPIS_BASE="${VITE_TAPIS_BASE_URL:-https://portals.tapis.io}"
TAPIS_HOST=$(echo "$TAPIS_BASE" | sed 's|https\?://||' | sed 's|/.*||')
cat > /etc/nginx/conf.d/tapis-proxy.inc << NGINXEOF
# Generated by docker-entrypoint.sh — do not edit manually.
resolver 8.8.8.8 1.1.1.1 valid=30s ipv6=off;
location /tapis-proxy/ {
    set \$tapis_upstream "${TAPIS_BASE}";
    rewrite ^/tapis-proxy/(.*) /\$1 break;
    proxy_pass \$tapis_upstream;
    proxy_ssl_server_name on;
    proxy_set_header Host ${TAPIS_HOST};
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_connect_timeout 10s;
}
NGINXEOF

exec "$@"
