/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bbox
 */
export interface Bbox {
}

/**
 * Check if a given object implements the Bbox interface.
 */
export function instanceOfBbox(value: object): value is Bbox {
    return true;
}

export function BboxFromJSON(json: any): Bbox {
    return BboxFromJSONTyped(json, false);
}

export function BboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bbox {
    return json;
}

export function BboxToJSON(json: any): Bbox {
    return BboxToJSONTyped(json, false);
}

export function BboxToJSONTyped(value?: Bbox | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

