/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BundleRequest
 */
export interface BundleRequest {
    /**
     * Base name for the pod bundle (e.g., sniffer)
     * @type {string}
     * @memberof BundleRequest
     */
    base: string;
    /**
     * Postgres username
     * @type {string}
     * @memberof BundleRequest
     */
    pgUser: string;
    /**
     * Postgres password
     * @type {string}
     * @memberof BundleRequest
     */
    pgPassword: string;
}

/**
 * Check if a given object implements the BundleRequest interface.
 */
export function instanceOfBundleRequest(value: object): value is BundleRequest {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('pgUser' in value) || value['pgUser'] === undefined) return false;
    if (!('pgPassword' in value) || value['pgPassword'] === undefined) return false;
    return true;
}

export function BundleRequestFromJSON(json: any): BundleRequest {
    return BundleRequestFromJSONTyped(json, false);
}

export function BundleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'pgUser': json['pg_user'],
        'pgPassword': json['pg_password'],
    };
}

export function BundleRequestToJSON(json: any): BundleRequest {
    return BundleRequestToJSONTyped(json, false);
}

export function BundleRequestToJSONTyped(value?: BundleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'pg_user': value['pgUser'],
        'pg_password': value['pgPassword'],
    };
}

