/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListCampaignsResponseItem } from './ListCampaignsResponseItem';
import {
    ListCampaignsResponseItemFromJSON,
    ListCampaignsResponseItemFromJSONTyped,
    ListCampaignsResponseItemToJSON,
    ListCampaignsResponseItemToJSONTyped,
} from './ListCampaignsResponseItem';

/**
 * 
 * @export
 * @interface CampaignPagination
 */
export interface CampaignPagination {
    /**
     * 
     * @type {Array<ListCampaignsResponseItem>}
     * @memberof CampaignPagination
     */
    items: Array<ListCampaignsResponseItem>;
    /**
     * 
     * @type {number}
     * @memberof CampaignPagination
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignPagination
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignPagination
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof CampaignPagination
     */
    pages: number;
}

/**
 * Check if a given object implements the CampaignPagination interface.
 */
export function instanceOfCampaignPagination(value: object): value is CampaignPagination {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    return true;
}

export function CampaignPaginationFromJSON(json: any): CampaignPagination {
    return CampaignPaginationFromJSONTyped(json, false);
}

export function CampaignPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ListCampaignsResponseItemFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'pages': json['pages'],
    };
}

export function CampaignPaginationToJSON(json: any): CampaignPagination {
    return CampaignPaginationToJSONTyped(json, false);
}

export function CampaignPaginationToJSONTyped(value?: CampaignPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ListCampaignsResponseItemToJSON)),
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
        'pages': value['pages'],
    };
}

