/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignUpdate
 */
export interface CampaignUpdate {
    /**
     * 
     * @type {string}
     * @memberof CampaignUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CampaignUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CampaignUpdate
     */
    contactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CampaignUpdate
     */
    contactEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CampaignUpdate
     */
    allocation?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CampaignUpdate
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CampaignUpdate
     */
    endDate?: Date | null;
}

/**
 * Check if a given object implements the CampaignUpdate interface.
 */
export function instanceOfCampaignUpdate(value: object): value is CampaignUpdate {
    return true;
}

export function CampaignUpdateFromJSON(json: any): CampaignUpdate {
    return CampaignUpdateFromJSONTyped(json, false);
}

export function CampaignUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'contactName': json['contact_name'] == null ? undefined : json['contact_name'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'allocation': json['allocation'] == null ? undefined : json['allocation'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
    };
}

export function CampaignUpdateToJSON(json: any): CampaignUpdate {
    return CampaignUpdateToJSONTyped(json, false);
}

export function CampaignUpdateToJSONTyped(value?: CampaignUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'contact_name': value['contactName'],
        'contact_email': value['contactEmail'],
        'allocation': value['allocation'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

