/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignCreateResponse
 */
export interface CampaignCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof CampaignCreateResponse
     */
    id: number;
}

/**
 * Check if a given object implements the CampaignCreateResponse interface.
 */
export function instanceOfCampaignCreateResponse(value: object): value is CampaignCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CampaignCreateResponseFromJSON(json: any): CampaignCreateResponse {
    return CampaignCreateResponseFromJSONTyped(json, false);
}

export function CampaignCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CampaignCreateResponseToJSON(json: any): CampaignCreateResponse {
    return CampaignCreateResponseToJSONTyped(json, false);
}

export function CampaignCreateResponseToJSONTyped(value?: CampaignCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

