"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCampaignPagination = instanceOfCampaignPagination;
exports.CampaignPaginationFromJSON = CampaignPaginationFromJSON;
exports.CampaignPaginationFromJSONTyped = CampaignPaginationFromJSONTyped;
exports.CampaignPaginationToJSON = CampaignPaginationToJSON;
exports.CampaignPaginationToJSONTyped = CampaignPaginationToJSONTyped;
var ListCampaignsResponseItem_1 = require("./ListCampaignsResponseItem");
/**
 * Check if a given object implements the CampaignPagination interface.
 */
function instanceOfCampaignPagination(value) {
    if (!('items' in value) || value['items'] === undefined)
        return false;
    if (!('total' in value) || value['total'] === undefined)
        return false;
    if (!('page' in value) || value['page'] === undefined)
        return false;
    if (!('size' in value) || value['size'] === undefined)
        return false;
    if (!('pages' in value) || value['pages'] === undefined)
        return false;
    return true;
}
function CampaignPaginationFromJSON(json) {
    return CampaignPaginationFromJSONTyped(json, false);
}
function CampaignPaginationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'items': (json['items'].map(ListCampaignsResponseItem_1.ListCampaignsResponseItemFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'pages': json['pages'],
    };
}
function CampaignPaginationToJSON(json) {
    return CampaignPaginationToJSONTyped(json, false);
}
function CampaignPaginationToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'items': (value['items'].map(ListCampaignsResponseItem_1.ListCampaignsResponseItemToJSON)),
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
        'pages': value['pages'],
    };
}
