/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForceUpdateSensorStatisticsResponse
 */
export interface ForceUpdateSensorStatisticsResponse {
    /**
     * 
     * @type {Array<number>}
     * @memberof ForceUpdateSensorStatisticsResponse
     */
    updatedSensorIds: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ForceUpdateSensorStatisticsResponse
     */
    totalUpdated: number;
}

/**
 * Check if a given object implements the ForceUpdateSensorStatisticsResponse interface.
 */
export function instanceOfForceUpdateSensorStatisticsResponse(value: object): value is ForceUpdateSensorStatisticsResponse {
    if (!('updatedSensorIds' in value) || value['updatedSensorIds'] === undefined) return false;
    if (!('totalUpdated' in value) || value['totalUpdated'] === undefined) return false;
    return true;
}

export function ForceUpdateSensorStatisticsResponseFromJSON(json: any): ForceUpdateSensorStatisticsResponse {
    return ForceUpdateSensorStatisticsResponseFromJSONTyped(json, false);
}

export function ForceUpdateSensorStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceUpdateSensorStatisticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'updatedSensorIds': json['updated_sensor_ids'],
        'totalUpdated': json['total_updated'],
    };
}

export function ForceUpdateSensorStatisticsResponseToJSON(json: any): ForceUpdateSensorStatisticsResponse {
    return ForceUpdateSensorStatisticsResponseToJSONTyped(json, false);
}

export function ForceUpdateSensorStatisticsResponseToJSONTyped(value?: ForceUpdateSensorStatisticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updated_sensor_ids': value['updatedSensorIds'],
        'total_updated': value['totalUpdated'],
    };
}

