"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetCampaignResponse = instanceOfGetCampaignResponse;
exports.GetCampaignResponseFromJSON = GetCampaignResponseFromJSON;
exports.GetCampaignResponseFromJSONTyped = GetCampaignResponseFromJSONTyped;
exports.GetCampaignResponseToJSON = GetCampaignResponseToJSON;
exports.GetCampaignResponseToJSONTyped = GetCampaignResponseToJSONTyped;
var SummaryGetCampaign_1 = require("./SummaryGetCampaign");
var Location_1 = require("./Location");
/**
 * Check if a given object implements the GetCampaignResponse interface.
 */
function instanceOfGetCampaignResponse(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('allocation' in value) || value['allocation'] === undefined)
        return false;
    if (!('summary' in value) || value['summary'] === undefined)
        return false;
    return true;
}
function GetCampaignResponseFromJSON(json) {
    return GetCampaignResponseFromJSONTyped(json, false);
}
function GetCampaignResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'contactName': json['contact_name'] == null ? undefined : json['contact_name'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'allocation': json['allocation'],
        'location': json['location'] == null ? undefined : (0, Location_1.LocationFromJSON)(json['location']),
        'summary': (0, SummaryGetCampaign_1.SummaryGetCampaignFromJSON)(json['summary']),
    };
}
function GetCampaignResponseToJSON(json) {
    return GetCampaignResponseToJSONTyped(json, false);
}
function GetCampaignResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'contact_name': value['contactName'],
        'contact_email': value['contactEmail'],
        'start_date': value['startDate'] == null ? undefined : (value['startDate'].toISOString()),
        'end_date': value['endDate'] == null ? undefined : (value['endDate'].toISOString()),
        'allocation': value['allocation'],
        'location': (0, Location_1.LocationToJSON)(value['location']),
        'summary': (0, SummaryGetCampaign_1.SummaryGetCampaignToJSON)(value['summary']),
    };
}
