/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SummaryGetCampaign } from './SummaryGetCampaign';
import {
    SummaryGetCampaignFromJSON,
    SummaryGetCampaignFromJSONTyped,
    SummaryGetCampaignToJSON,
    SummaryGetCampaignToJSONTyped,
} from './SummaryGetCampaign';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface GetCampaignResponse
 */
export interface GetCampaignResponse {
    /**
     * 
     * @type {number}
     * @memberof GetCampaignResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetCampaignResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetCampaignResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaignResponse
     */
    contactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaignResponse
     */
    contactEmail?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetCampaignResponse
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GetCampaignResponse
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaignResponse
     */
    allocation: string;
    /**
     * 
     * @type {Location}
     * @memberof GetCampaignResponse
     */
    location?: Location | null;
    /**
     * 
     * @type {SummaryGetCampaign}
     * @memberof GetCampaignResponse
     */
    summary: SummaryGetCampaign;
}

/**
 * Check if a given object implements the GetCampaignResponse interface.
 */
export function instanceOfGetCampaignResponse(value: object): value is GetCampaignResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('allocation' in value) || value['allocation'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function GetCampaignResponseFromJSON(json: any): GetCampaignResponse {
    return GetCampaignResponseFromJSONTyped(json, false);
}

export function GetCampaignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCampaignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'contactName': json['contact_name'] == null ? undefined : json['contact_name'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'allocation': json['allocation'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
        'summary': SummaryGetCampaignFromJSON(json['summary']),
    };
}

export function GetCampaignResponseToJSON(json: any): GetCampaignResponse {
    return GetCampaignResponseToJSONTyped(json, false);
}

export function GetCampaignResponseToJSONTyped(value?: GetCampaignResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'contact_name': value['contactName'],
        'contact_email': value['contactEmail'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'allocation': value['allocation'],
        'location': LocationToJSON(value['location']),
        'summary': SummaryGetCampaignToJSON(value['summary']),
    };
}

