/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSensorResponse
 */
export interface GetSensorResponse {
    /**
     * 
     * @type {number}
     * @memberof GetSensorResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    alias?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetSensorResponse
     */
    postprocess?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    postprocessscript?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    units?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    variablename?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetSensorResponse
     */
    maxValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSensorResponse
     */
    minValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSensorResponse
     */
    avgValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSensorResponse
     */
    count?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof GetSensorResponse
     */
    firstMeasurementTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GetSensorResponse
     */
    lastMeasurementTime?: Date | null;
}

/**
 * Check if a given object implements the GetSensorResponse interface.
 */
export function instanceOfGetSensorResponse(value: object): value is GetSensorResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetSensorResponseFromJSON(json: any): GetSensorResponse {
    return GetSensorResponseFromJSONTyped(json, false);
}

export function GetSensorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSensorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'description': json['description'] == null ? undefined : json['description'],
        'postprocess': json['postprocess'] == null ? undefined : json['postprocess'],
        'postprocessscript': json['postprocessscript'] == null ? undefined : json['postprocessscript'],
        'units': json['units'] == null ? undefined : json['units'],
        'variablename': json['variablename'] == null ? undefined : json['variablename'],
        'maxValue': json['max_value'] == null ? undefined : json['max_value'],
        'minValue': json['min_value'] == null ? undefined : json['min_value'],
        'avgValue': json['avg_value'] == null ? undefined : json['avg_value'],
        'count': json['count'] == null ? undefined : json['count'],
        'firstMeasurementTime': json['first_measurement_time'] == null ? undefined : (new Date(json['first_measurement_time'])),
        'lastMeasurementTime': json['last_measurement_time'] == null ? undefined : (new Date(json['last_measurement_time'])),
    };
}

export function GetSensorResponseToJSON(json: any): GetSensorResponse {
    return GetSensorResponseToJSONTyped(json, false);
}

export function GetSensorResponseToJSONTyped(value?: GetSensorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'alias': value['alias'],
        'description': value['description'],
        'postprocess': value['postprocess'],
        'postprocessscript': value['postprocessscript'],
        'units': value['units'],
        'variablename': value['variablename'],
        'max_value': value['maxValue'],
        'min_value': value['minValue'],
        'avg_value': value['avgValue'],
        'count': value['count'],
        'first_measurement_time': value['firstMeasurementTime'] == null ? undefined : ((value['firstMeasurementTime'] as any).toISOString()),
        'last_measurement_time': value['lastMeasurementTime'] == null ? undefined : ((value['lastMeasurementTime'] as any).toISOString()),
    };
}

