/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorStatistics } from './SensorStatistics';
import {
    SensorStatisticsFromJSON,
    SensorStatisticsFromJSONTyped,
    SensorStatisticsToJSON,
    SensorStatisticsToJSONTyped,
} from './SensorStatistics';

/**
 * 
 * @export
 * @interface GetSensorResponse
 */
export interface GetSensorResponse {
    /**
     * 
     * @type {number}
     * @memberof GetSensorResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    alias?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetSensorResponse
     */
    postprocess?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    postprocessscript?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    units?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSensorResponse
     */
    variablename?: string | null;
    /**
     * 
     * @type {SensorStatistics}
     * @memberof GetSensorResponse
     */
    statistics?: SensorStatistics | null;
}

/**
 * Check if a given object implements the GetSensorResponse interface.
 */
export function instanceOfGetSensorResponse(value: object): value is GetSensorResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetSensorResponseFromJSON(json: any): GetSensorResponse {
    return GetSensorResponseFromJSONTyped(json, false);
}

export function GetSensorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSensorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'description': json['description'] == null ? undefined : json['description'],
        'postprocess': json['postprocess'] == null ? undefined : json['postprocess'],
        'postprocessscript': json['postprocessscript'] == null ? undefined : json['postprocessscript'],
        'units': json['units'] == null ? undefined : json['units'],
        'variablename': json['variablename'] == null ? undefined : json['variablename'],
        'statistics': json['statistics'] == null ? undefined : SensorStatisticsFromJSON(json['statistics']),
    };
}

export function GetSensorResponseToJSON(json: any): GetSensorResponse {
    return GetSensorResponseToJSONTyped(json, false);
}

export function GetSensorResponseToJSONTyped(value?: GetSensorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'alias': value['alias'],
        'description': value['description'],
        'postprocess': value['postprocess'],
        'postprocessscript': value['postprocessscript'],
        'units': value['units'],
        'variablename': value['variablename'],
        'statistics': SensorStatisticsToJSON(value['statistics']),
    };
}

