/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineStringCoordinatesInner
 */
export interface LineStringCoordinatesInner {
}

/**
 * Check if a given object implements the LineStringCoordinatesInner interface.
 */
export function instanceOfLineStringCoordinatesInner(value: object): value is LineStringCoordinatesInner {
    return true;
}

export function LineStringCoordinatesInnerFromJSON(json: any): LineStringCoordinatesInner {
    return LineStringCoordinatesInnerFromJSONTyped(json, false);
}

export function LineStringCoordinatesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineStringCoordinatesInner {
    return json;
}

export function LineStringCoordinatesInnerToJSON(json: any): LineStringCoordinatesInner {
    return LineStringCoordinatesInnerToJSONTyped(json, false);
}

export function LineStringCoordinatesInnerToJSONTyped(value?: LineStringCoordinatesInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

