/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SummaryListCampaigns } from './SummaryListCampaigns';
import {
    SummaryListCampaignsFromJSON,
    SummaryListCampaignsFromJSONTyped,
    SummaryListCampaignsToJSON,
    SummaryListCampaignsToJSONTyped,
} from './SummaryListCampaigns';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface ListCampaignsResponseItem
 */
export interface ListCampaignsResponseItem {
    /**
     * 
     * @type {number}
     * @memberof ListCampaignsResponseItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ListCampaignsResponseItem
     */
    name: string;
    /**
     * 
     * @type {Location}
     * @memberof ListCampaignsResponseItem
     */
    location?: Location | null;
    /**
     * 
     * @type {string}
     * @memberof ListCampaignsResponseItem
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListCampaignsResponseItem
     */
    contactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListCampaignsResponseItem
     */
    contactEmail?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListCampaignsResponseItem
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListCampaignsResponseItem
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ListCampaignsResponseItem
     */
    allocation?: string | null;
    /**
     * 
     * @type {SummaryListCampaigns}
     * @memberof ListCampaignsResponseItem
     */
    summary: SummaryListCampaigns;
}

/**
 * Check if a given object implements the ListCampaignsResponseItem interface.
 */
export function instanceOfListCampaignsResponseItem(value: object): value is ListCampaignsResponseItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function ListCampaignsResponseItemFromJSON(json: any): ListCampaignsResponseItem {
    return ListCampaignsResponseItemFromJSONTyped(json, false);
}

export function ListCampaignsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCampaignsResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
        'description': json['description'] == null ? undefined : json['description'],
        'contactName': json['contact_name'] == null ? undefined : json['contact_name'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'allocation': json['allocation'] == null ? undefined : json['allocation'],
        'summary': SummaryListCampaignsFromJSON(json['summary']),
    };
}

export function ListCampaignsResponseItemToJSON(json: any): ListCampaignsResponseItem {
    return ListCampaignsResponseItemToJSONTyped(json, false);
}

export function ListCampaignsResponseItemToJSONTyped(value?: ListCampaignsResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'location': LocationToJSON(value['location']),
        'description': value['description'],
        'contact_name': value['contactName'],
        'contact_email': value['contactEmail'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'allocation': value['allocation'],
        'summary': SummaryListCampaignsToJSON(value['summary']),
    };
}

