/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StationItemWithSummary } from './StationItemWithSummary';
import {
    StationItemWithSummaryFromJSON,
    StationItemWithSummaryFromJSONTyped,
    StationItemWithSummaryToJSON,
    StationItemWithSummaryToJSONTyped,
} from './StationItemWithSummary';

/**
 * 
 * @export
 * @interface ListStationsResponsePagination
 */
export interface ListStationsResponsePagination {
    /**
     * 
     * @type {Array<StationItemWithSummary>}
     * @memberof ListStationsResponsePagination
     */
    items: Array<StationItemWithSummary>;
    /**
     * 
     * @type {number}
     * @memberof ListStationsResponsePagination
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ListStationsResponsePagination
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ListStationsResponsePagination
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof ListStationsResponsePagination
     */
    pages: number;
}

/**
 * Check if a given object implements the ListStationsResponsePagination interface.
 */
export function instanceOfListStationsResponsePagination(value: object): value is ListStationsResponsePagination {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    return true;
}

export function ListStationsResponsePaginationFromJSON(json: any): ListStationsResponsePagination {
    return ListStationsResponsePaginationFromJSONTyped(json, false);
}

export function ListStationsResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListStationsResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(StationItemWithSummaryFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'pages': json['pages'],
    };
}

export function ListStationsResponsePaginationToJSON(json: any): ListStationsResponsePagination {
    return ListStationsResponsePaginationToJSONTyped(json, false);
}

export function ListStationsResponsePaginationToJSONTyped(value?: ListStationsResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(StationItemWithSummaryToJSON)),
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
        'pages': value['pages'],
    };
}

