/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoteItem } from './NoteItem';
import {
    NoteItemFromJSON,
    NoteItemFromJSONTyped,
    NoteItemToJSON,
    NoteItemToJSONTyped,
} from './NoteItem';

/**
 * 
 * @export
 * @interface ListNotesResponse
 */
export interface ListNotesResponse {
    /**
     * 
     * @type {Array<NoteItem>}
     * @memberof ListNotesResponse
     */
    items: Array<NoteItem>;
    /**
     * 
     * @type {number}
     * @memberof ListNotesResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ListNotesResponse interface.
 */
export function instanceOfListNotesResponse(value: object): value is ListNotesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ListNotesResponseFromJSON(json: any): ListNotesResponse {
    return ListNotesResponseFromJSONTyped(json, false);
}

export function ListNotesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNotesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(NoteItemFromJSON)),
        'total': json['total'],
    };
}

export function ListNotesResponseToJSON(json: any): ListNotesResponse {
    return ListNotesResponseToJSONTyped(json, false);
}

export function ListNotesResponseToJSONTyped(value?: ListNotesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(NoteItemToJSON)),
        'total': value['total'],
    };
}

