"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfLocation = instanceOfLocation;
exports.LocationFromJSON = LocationFromJSON;
exports.LocationFromJSONTyped = LocationFromJSONTyped;
exports.LocationToJSON = LocationToJSON;
exports.LocationToJSONTyped = LocationToJSONTyped;
/**
 * Check if a given object implements the Location interface.
 */
function instanceOfLocation(value) {
    return true;
}
function LocationFromJSON(json) {
    return LocationFromJSONTyped(json, false);
}
function LocationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'bboxWest': json['bbox_west'] == null ? undefined : json['bbox_west'],
        'bboxEast': json['bbox_east'] == null ? undefined : json['bbox_east'],
        'bboxSouth': json['bbox_south'] == null ? undefined : json['bbox_south'],
        'bboxNorth': json['bbox_north'] == null ? undefined : json['bbox_north'],
    };
}
function LocationToJSON(json) {
    return LocationToJSONTyped(json, false);
}
function LocationToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'bbox_west': value['bboxWest'],
        'bbox_east': value['bboxEast'],
        'bbox_south': value['bboxSouth'],
        'bbox_north': value['bboxNorth'],
    };
}
