/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    bboxWest?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    bboxEast?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    bboxSouth?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    bboxNorth?: number | null;
}

/**
 * Check if a given object implements the Location interface.
 */
export function instanceOfLocation(value: object): value is Location {
    return true;
}

export function LocationFromJSON(json: any): Location {
    return LocationFromJSONTyped(json, false);
}

export function LocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Location {
    if (json == null) {
        return json;
    }
    return {
        
        'bboxWest': json['bbox_west'] == null ? undefined : json['bbox_west'],
        'bboxEast': json['bbox_east'] == null ? undefined : json['bbox_east'],
        'bboxSouth': json['bbox_south'] == null ? undefined : json['bbox_south'],
        'bboxNorth': json['bbox_north'] == null ? undefined : json['bbox_north'],
    };
}

export function LocationToJSON(json: any): Location {
    return LocationToJSONTyped(json, false);
}

export function LocationToJSONTyped(value?: Location | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox_west': value['bboxWest'],
        'bbox_east': value['bboxEast'],
        'bbox_south': value['bboxSouth'],
        'bbox_north': value['bboxNorth'],
    };
}

