/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Location1Inner
 */
export interface Location1Inner {
}

/**
 * Check if a given object implements the Location1Inner interface.
 */
export function instanceOfLocation1Inner(value: object): value is Location1Inner {
    return true;
}

export function Location1InnerFromJSON(json: any): Location1Inner {
    return Location1InnerFromJSONTyped(json, false);
}

export function Location1InnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Location1Inner {
    return json;
}

export function Location1InnerToJSON(json: any): Location1Inner {
    return Location1InnerToJSONTyped(json, false);
}

export function Location1InnerToJSONTyped(value?: Location1Inner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

