/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    tokenType: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    tapisAccessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    tapisRefreshToken?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    tapisExpiresAt?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    role?: string | null;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'tapisAccessToken': json['tapis_access_token'] == null ? undefined : json['tapis_access_token'],
        'tapisRefreshToken': json['tapis_refresh_token'] == null ? undefined : json['tapis_refresh_token'],
        'tapisExpiresAt': json['tapis_expires_at'] == null ? undefined : json['tapis_expires_at'],
        'username': json['username'] == null ? undefined : json['username'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function LoginResponseToJSON(json: any): LoginResponse {
    return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'tapis_access_token': value['tapisAccessToken'],
        'tapis_refresh_token': value['tapisRefreshToken'],
        'tapis_expires_at': value['tapisExpiresAt'],
        'username': value['username'],
        'role': value['role'],
    };
}

