/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeasurementCreateResponse
 */
export interface MeasurementCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof MeasurementCreateResponse
     */
    id: number;
}

/**
 * Check if a given object implements the MeasurementCreateResponse interface.
 */
export function instanceOfMeasurementCreateResponse(value: object): value is MeasurementCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MeasurementCreateResponseFromJSON(json: any): MeasurementCreateResponse {
    return MeasurementCreateResponseFromJSONTyped(json, false);
}

export function MeasurementCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function MeasurementCreateResponseToJSON(json: any): MeasurementCreateResponse {
    return MeasurementCreateResponseToJSONTyped(json, false);
}

export function MeasurementCreateResponseToJSONTyped(value?: MeasurementCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

