/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeasurementIn
 */
export interface MeasurementIn {
    /**
     * 
     * @type {number}
     * @memberof MeasurementIn
     */
    sensorid?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof MeasurementIn
     */
    collectiontime: Date;
    /**
     * 
     * @type {string}
     * @memberof MeasurementIn
     */
    geometry?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MeasurementIn
     */
    measurementvalue: number;
    /**
     * 
     * @type {string}
     * @memberof MeasurementIn
     */
    variablename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeasurementIn
     */
    variabletype?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeasurementIn
     */
    description?: string | null;
}

/**
 * Check if a given object implements the MeasurementIn interface.
 */
export function instanceOfMeasurementIn(value: object): value is MeasurementIn {
    if (!('collectiontime' in value) || value['collectiontime'] === undefined) return false;
    if (!('measurementvalue' in value) || value['measurementvalue'] === undefined) return false;
    return true;
}

export function MeasurementInFromJSON(json: any): MeasurementIn {
    return MeasurementInFromJSONTyped(json, false);
}

export function MeasurementInFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementIn {
    if (json == null) {
        return json;
    }
    return {
        
        'sensorid': json['sensorid'] == null ? undefined : json['sensorid'],
        'collectiontime': (new Date(json['collectiontime'])),
        'geometry': json['geometry'] == null ? undefined : json['geometry'],
        'measurementvalue': json['measurementvalue'],
        'variablename': json['variablename'] == null ? undefined : json['variablename'],
        'variabletype': json['variabletype'] == null ? undefined : json['variabletype'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function MeasurementInToJSON(json: any): MeasurementIn {
    return MeasurementInToJSONTyped(json, false);
}

export function MeasurementInToJSONTyped(value?: MeasurementIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sensorid': value['sensorid'],
        'collectiontime': ((value['collectiontime']).toISOString()),
        'geometry': value['geometry'],
        'measurementvalue': value['measurementvalue'],
        'variablename': value['variablename'],
        'variabletype': value['variabletype'],
        'description': value['description'],
    };
}

