/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Full-replacement semantics, matching `content` on the base NoteUpdate:
 * always send the desired location, or omit/null to clear it.
 * @export
 * @interface MeasurementNoteUpdate
 */
export interface MeasurementNoteUpdate {
    /**
     * 
     * @type {string}
     * @memberof MeasurementNoteUpdate
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof MeasurementNoteUpdate
     */
    location?: string | null;
}

/**
 * Check if a given object implements the MeasurementNoteUpdate interface.
 */
export function instanceOfMeasurementNoteUpdate(value: object): value is MeasurementNoteUpdate {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function MeasurementNoteUpdateFromJSON(json: any): MeasurementNoteUpdate {
    return MeasurementNoteUpdateFromJSONTyped(json, false);
}

export function MeasurementNoteUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementNoteUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function MeasurementNoteUpdateToJSON(json: any): MeasurementNoteUpdate {
    return MeasurementNoteUpdateToJSONTyped(json, false);
}

export function MeasurementNoteUpdateToJSONTyped(value?: MeasurementNoteUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'location': value['location'],
    };
}

