/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeasurementItem
 */
export interface MeasurementItem {
    /**
     * 
     * @type {number}
     * @memberof MeasurementItem
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementItem
     */
    sensorid?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MeasurementItem
     */
    variablename?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MeasurementItem
     */
    collectiontime: Date;
    /**
     * 
     * @type {string}
     * @memberof MeasurementItem
     */
    variabletype?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeasurementItem
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MeasurementItem
     */
    value?: number | null;
}

/**
 * Check if a given object implements the MeasurementItem interface.
 */
export function instanceOfMeasurementItem(value: object): value is MeasurementItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('collectiontime' in value) || value['collectiontime'] === undefined) return false;
    return true;
}

export function MeasurementItemFromJSON(json: any): MeasurementItem {
    return MeasurementItemFromJSONTyped(json, false);
}

export function MeasurementItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sensorid': json['sensorid'] == null ? undefined : json['sensorid'],
        'variablename': json['variablename'] == null ? undefined : json['variablename'],
        'collectiontime': (new Date(json['collectiontime'])),
        'variabletype': json['variabletype'] == null ? undefined : json['variabletype'],
        'description': json['description'] == null ? undefined : json['description'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MeasurementItemToJSON(json: any): MeasurementItem {
    return MeasurementItemToJSONTyped(json, false);
}

export function MeasurementItemToJSONTyped(value?: MeasurementItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sensorid': value['sensorid'],
        'variablename': value['variablename'],
        'collectiontime': ((value['collectiontime']).toISOString()),
        'variabletype': value['variabletype'],
        'description': value['description'],
        'value': value['value'],
    };
}

