/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeResponse
 */
export interface MeResponse {
    /**
     * 
     * @type {string}
     * @memberof MeResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof MeResponse
     */
    role?: string | null;
}

/**
 * Check if a given object implements the MeResponse interface.
 */
export function instanceOfMeResponse(value: object): value is MeResponse {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function MeResponseFromJSON(json: any): MeResponse {
    return MeResponseFromJSONTyped(json, false);
}

export function MeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function MeResponseToJSON(json: any): MeResponse {
    return MeResponseToJSONTyped(json, false);
}

export function MeResponseToJSONTyped(value?: MeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'role': value['role'],
    };
}

