/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataSchemaUpdate
 */
export interface MetadataSchemaUpdate {
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    scope?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    label?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    fieldType?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataSchemaUpdate
     */
    required?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    helpText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    units?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    ckanField?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaUpdate
     */
    ckanMode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MetadataSchemaUpdate
     */
    orderIndex?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataSchemaUpdate
     */
    active?: boolean | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MetadataSchemaUpdate
     */
    options?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the MetadataSchemaUpdate interface.
 */
export function instanceOfMetadataSchemaUpdate(value: object): value is MetadataSchemaUpdate {
    return true;
}

export function MetadataSchemaUpdateFromJSON(json: any): MetadataSchemaUpdate {
    return MetadataSchemaUpdateFromJSONTyped(json, false);
}

export function MetadataSchemaUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataSchemaUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'] == null ? undefined : json['scope'],
        'key': json['key'] == null ? undefined : json['key'],
        'label': json['label'] == null ? undefined : json['label'],
        'fieldType': json['field_type'] == null ? undefined : json['field_type'],
        'required': json['required'] == null ? undefined : json['required'],
        'helpText': json['help_text'] == null ? undefined : json['help_text'],
        'units': json['units'] == null ? undefined : json['units'],
        'ckanField': json['ckan_field'] == null ? undefined : json['ckan_field'],
        'ckanMode': json['ckan_mode'] == null ? undefined : json['ckan_mode'],
        'orderIndex': json['order_index'] == null ? undefined : json['order_index'],
        'active': json['active'] == null ? undefined : json['active'],
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function MetadataSchemaUpdateToJSON(json: any): MetadataSchemaUpdate {
    return MetadataSchemaUpdateToJSONTyped(json, false);
}

export function MetadataSchemaUpdateToJSONTyped(value?: MetadataSchemaUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'key': value['key'],
        'label': value['label'],
        'field_type': value['fieldType'],
        'required': value['required'],
        'help_text': value['helpText'],
        'units': value['units'],
        'ckan_field': value['ckanField'],
        'ckan_mode': value['ckanMode'],
        'order_index': value['orderIndex'],
        'active': value['active'],
        'options': value['options'],
    };
}

