/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataSchemaResponse } from './MetadataSchemaResponse';
import {
    MetadataSchemaResponseFromJSON,
    MetadataSchemaResponseFromJSONTyped,
    MetadataSchemaResponseToJSON,
    MetadataSchemaResponseToJSONTyped,
} from './MetadataSchemaResponse';

/**
 * 
 * @export
 * @interface MetadataSchemaListResponse
 */
export interface MetadataSchemaListResponse {
    /**
     * 
     * @type {Array<MetadataSchemaResponse>}
     * @memberof MetadataSchemaListResponse
     */
    items: Array<MetadataSchemaResponse>;
}

/**
 * Check if a given object implements the MetadataSchemaListResponse interface.
 */
export function instanceOfMetadataSchemaListResponse(value: object): value is MetadataSchemaListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function MetadataSchemaListResponseFromJSON(json: any): MetadataSchemaListResponse {
    return MetadataSchemaListResponseFromJSONTyped(json, false);
}

export function MetadataSchemaListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataSchemaListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MetadataSchemaResponseFromJSON)),
    };
}

export function MetadataSchemaListResponseToJSON(json: any): MetadataSchemaListResponse {
    return MetadataSchemaListResponseToJSONTyped(json, false);
}

export function MetadataSchemaListResponseToJSONTyped(value?: MetadataSchemaListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MetadataSchemaResponseToJSON)),
    };
}

