/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataSchemaResponse
 */
export interface MetadataSchemaResponse {
    /**
     * Scope for the metadata field (campaign, station, sensor)
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    scope: string;
    /**
     * Unique key for this metadata field within the scope
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    key: string;
    /**
     * Human-readable label
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    label: string;
    /**
     * string | number | date | enum | bool | json
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    fieldType: string;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataSchemaResponse
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    helpText?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    units?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    ckanField?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataSchemaResponse
     */
    ckanMode?: string;
    /**
     * 
     * @type {number}
     * @memberof MetadataSchemaResponse
     */
    orderIndex?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataSchemaResponse
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MetadataSchemaResponse
     */
    options?: { [key: string]: any; } | null;
    /**
     * 
     * @type {number}
     * @memberof MetadataSchemaResponse
     */
    id: number;
}

/**
 * Check if a given object implements the MetadataSchemaResponse interface.
 */
export function instanceOfMetadataSchemaResponse(value: object): value is MetadataSchemaResponse {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('fieldType' in value) || value['fieldType'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MetadataSchemaResponseFromJSON(json: any): MetadataSchemaResponse {
    return MetadataSchemaResponseFromJSONTyped(json, false);
}

export function MetadataSchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataSchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
        'key': json['key'],
        'label': json['label'],
        'fieldType': json['field_type'],
        'required': json['required'] == null ? undefined : json['required'],
        'helpText': json['help_text'] == null ? undefined : json['help_text'],
        'units': json['units'] == null ? undefined : json['units'],
        'ckanField': json['ckan_field'] == null ? undefined : json['ckan_field'],
        'ckanMode': json['ckan_mode'] == null ? undefined : json['ckan_mode'],
        'orderIndex': json['order_index'] == null ? undefined : json['order_index'],
        'active': json['active'] == null ? undefined : json['active'],
        'options': json['options'] == null ? undefined : json['options'],
        'id': json['id'],
    };
}

export function MetadataSchemaResponseToJSON(json: any): MetadataSchemaResponse {
    return MetadataSchemaResponseToJSONTyped(json, false);
}

export function MetadataSchemaResponseToJSONTyped(value?: MetadataSchemaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'key': value['key'],
        'label': value['label'],
        'field_type': value['fieldType'],
        'required': value['required'],
        'help_text': value['helpText'],
        'units': value['units'],
        'ckan_field': value['ckanField'],
        'ckan_mode': value['ckanMode'],
        'order_index': value['orderIndex'],
        'active': value['active'],
        'options': value['options'],
        'id': value['id'],
    };
}

