/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bbox } from './Bbox';
import {
    BboxFromJSON,
    BboxFromJSONTyped,
    BboxToJSON,
    BboxToJSONTyped,
} from './Bbox';
import type { LineStringCoordinatesInner } from './LineStringCoordinatesInner';
import {
    LineStringCoordinatesInnerFromJSON,
    LineStringCoordinatesInnerFromJSONTyped,
    LineStringCoordinatesInnerToJSON,
    LineStringCoordinatesInnerToJSONTyped,
} from './LineStringCoordinatesInner';

/**
 * MultiLineString Model
 * @export
 * @interface MultiLineString
 */
export interface MultiLineString {
    /**
     * 
     * @type {Bbox}
     * @memberof MultiLineString
     */
    bbox?: Bbox | null;
    /**
     * 
     * @type {string}
     * @memberof MultiLineString
     */
    type: MultiLineStringTypeEnum;
    /**
     * 
     * @type {Array<Array<LineStringCoordinatesInner>>}
     * @memberof MultiLineString
     */
    coordinates: Array<Array<LineStringCoordinatesInner>>;
}


/**
 * @export
 */
export const MultiLineStringTypeEnum = {
    MultiLineString: 'MultiLineString'
} as const;
export type MultiLineStringTypeEnum = typeof MultiLineStringTypeEnum[keyof typeof MultiLineStringTypeEnum];


/**
 * Check if a given object implements the MultiLineString interface.
 */
export function instanceOfMultiLineString(value: object): value is MultiLineString {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function MultiLineStringFromJSON(json: any): MultiLineString {
    return MultiLineStringFromJSONTyped(json, false);
}

export function MultiLineStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiLineString {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BboxFromJSON(json['bbox']),
        'type': json['type'],
        'coordinates': json['coordinates'],
    };
}

export function MultiLineStringToJSON(json: any): MultiLineString {
    return MultiLineStringToJSONTyped(json, false);
}

export function MultiLineStringToJSONTyped(value?: MultiLineString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': BboxToJSON(value['bbox']),
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

