/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bbox } from './Bbox';
import {
    BboxFromJSON,
    BboxFromJSONTyped,
    BboxToJSON,
    BboxToJSONTyped,
} from './Bbox';
import type { LineStringCoordinatesInner } from './LineStringCoordinatesInner';
import {
    LineStringCoordinatesInnerFromJSON,
    LineStringCoordinatesInnerFromJSONTyped,
    LineStringCoordinatesInnerToJSON,
    LineStringCoordinatesInnerToJSONTyped,
} from './LineStringCoordinatesInner';

/**
 * MultiPoint Model
 * @export
 * @interface MultiPoint
 */
export interface MultiPoint {
    /**
     * 
     * @type {Bbox}
     * @memberof MultiPoint
     */
    bbox?: Bbox | null;
    /**
     * 
     * @type {string}
     * @memberof MultiPoint
     */
    type: MultiPointTypeEnum;
    /**
     * 
     * @type {Array<LineStringCoordinatesInner>}
     * @memberof MultiPoint
     */
    coordinates: Array<LineStringCoordinatesInner>;
}


/**
 * @export
 */
export const MultiPointTypeEnum = {
    MultiPoint: 'MultiPoint'
} as const;
export type MultiPointTypeEnum = typeof MultiPointTypeEnum[keyof typeof MultiPointTypeEnum];


/**
 * Check if a given object implements the MultiPoint interface.
 */
export function instanceOfMultiPoint(value: object): value is MultiPoint {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function MultiPointFromJSON(json: any): MultiPoint {
    return MultiPointFromJSONTyped(json, false);
}

export function MultiPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BboxFromJSON(json['bbox']),
        'type': json['type'],
        'coordinates': ((json['coordinates'] as Array<any>).map(LineStringCoordinatesInnerFromJSON)),
    };
}

export function MultiPointToJSON(json: any): MultiPoint {
    return MultiPointToJSONTyped(json, false);
}

export function MultiPointToJSONTyped(value?: MultiPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': BboxToJSON(value['bbox']),
        'type': value['type'],
        'coordinates': ((value['coordinates'] as Array<any>).map(LineStringCoordinatesInnerToJSON)),
    };
}

