/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bbox } from './Bbox';
import {
    BboxFromJSON,
    BboxFromJSONTyped,
    BboxToJSON,
    BboxToJSONTyped,
} from './Bbox';
import type { LineStringCoordinatesInner } from './LineStringCoordinatesInner';
import {
    LineStringCoordinatesInnerFromJSON,
    LineStringCoordinatesInnerFromJSONTyped,
    LineStringCoordinatesInnerToJSON,
    LineStringCoordinatesInnerToJSONTyped,
} from './LineStringCoordinatesInner';

/**
 * MultiPolygon Model
 * @export
 * @interface MultiPolygon
 */
export interface MultiPolygon {
    /**
     * 
     * @type {Bbox}
     * @memberof MultiPolygon
     */
    bbox?: Bbox | null;
    /**
     * 
     * @type {string}
     * @memberof MultiPolygon
     */
    type: MultiPolygonTypeEnum;
    /**
     * 
     * @type {Array<Array<Array<LineStringCoordinatesInner>>>}
     * @memberof MultiPolygon
     */
    coordinates: Array<Array<Array<LineStringCoordinatesInner>>>;
}


/**
 * @export
 */
export const MultiPolygonTypeEnum = {
    MultiPolygon: 'MultiPolygon'
} as const;
export type MultiPolygonTypeEnum = typeof MultiPolygonTypeEnum[keyof typeof MultiPolygonTypeEnum];


/**
 * Check if a given object implements the MultiPolygon interface.
 */
export function instanceOfMultiPolygon(value: object): value is MultiPolygon {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function MultiPolygonFromJSON(json: any): MultiPolygon {
    return MultiPolygonFromJSONTyped(json, false);
}

export function MultiPolygonFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPolygon {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BboxFromJSON(json['bbox']),
        'type': json['type'],
        'coordinates': json['coordinates'],
    };
}

export function MultiPolygonToJSON(json: any): MultiPolygon {
    return MultiPolygonToJSONTyped(json, false);
}

export function MultiPolygonToJSONTyped(value?: MultiPolygon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': BboxToJSON(value['bbox']),
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

