/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NoteScope = {
    Campaign: 'campaign',
    Station: 'station',
    Sensor: 'sensor',
    Measurement: 'measurement'
} as const;
export type NoteScope = typeof NoteScope[keyof typeof NoteScope];


export function instanceOfNoteScope(value: any): boolean {
    for (const key in NoteScope) {
        if (Object.prototype.hasOwnProperty.call(NoteScope, key)) {
            if (NoteScope[key as keyof typeof NoteScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NoteScopeFromJSON(json: any): NoteScope {
    return NoteScopeFromJSONTyped(json, false);
}

export function NoteScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteScope {
    return json as NoteScope;
}

export function NoteScopeToJSON(value?: NoteScope | null): any {
    return value as any;
}

export function NoteScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): NoteScope {
    return value as NoteScope;
}

