/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoteScope } from './NoteScope';
import {
    NoteScopeFromJSON,
    NoteScopeFromJSONTyped,
    NoteScopeToJSON,
    NoteScopeToJSONTyped,
} from './NoteScope';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
    PointToJSONTyped,
} from './Point';

/**
 * 
 * @export
 * @interface NoteItem
 */
export interface NoteItem {
    /**
     * 
     * @type {number}
     * @memberof NoteItem
     */
    id: number;
    /**
     * 
     * @type {NoteScope}
     * @memberof NoteItem
     */
    scope: NoteScope;
    /**
     * 
     * @type {string}
     * @memberof NoteItem
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof NoteItem
     */
    createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof NoteItem
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof NoteItem
     */
    campaignId: number;
    /**
     * 
     * @type {number}
     * @memberof NoteItem
     */
    stationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NoteItem
     */
    sensorId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NoteItem
     */
    measurementId?: number | null;
    /**
     * 
     * @type {Point}
     * @memberof NoteItem
     */
    location?: Point | null;
}



/**
 * Check if a given object implements the NoteItem interface.
 */
export function instanceOfNoteItem(value: object): value is NoteItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    return true;
}

export function NoteItemFromJSON(json: any): NoteItem {
    return NoteItemFromJSONTyped(json, false);
}

export function NoteItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scope': NoteScopeFromJSON(json['scope']),
        'content': json['content'],
        'createdBy': json['created_by'],
        'createdAt': (new Date(json['created_at'])),
        'campaignId': json['campaign_id'],
        'stationId': json['station_id'] == null ? undefined : json['station_id'],
        'sensorId': json['sensor_id'] == null ? undefined : json['sensor_id'],
        'measurementId': json['measurement_id'] == null ? undefined : json['measurement_id'],
        'location': json['location'] == null ? undefined : PointFromJSON(json['location']),
    };
}

export function NoteItemToJSON(json: any): NoteItem {
    return NoteItemToJSONTyped(json, false);
}

export function NoteItemToJSONTyped(value?: NoteItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'scope': NoteScopeToJSON(value['scope']),
        'content': value['content'],
        'created_by': value['createdBy'],
        'created_at': ((value['createdAt']).toISOString()),
        'campaign_id': value['campaignId'],
        'station_id': value['stationId'],
        'sensor_id': value['sensorId'],
        'measurement_id': value['measurementId'],
        'location': PointToJSON(value['location']),
    };
}

