/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteCreateResponse
 */
export interface NoteCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof NoteCreateResponse
     */
    id: number;
}

/**
 * Check if a given object implements the NoteCreateResponse interface.
 */
export function instanceOfNoteCreateResponse(value: object): value is NoteCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function NoteCreateResponseFromJSON(json: any): NoteCreateResponse {
    return NoteCreateResponseFromJSONTyped(json, false);
}

export function NoteCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function NoteCreateResponseToJSON(json: any): NoteCreateResponse {
    return NoteCreateResponseToJSONTyped(json, false);
}

export function NoteCreateResponseToJSONTyped(value?: NoteCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

