/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteUpdate
 */
export interface NoteUpdate {
    /**
     * 
     * @type {string}
     * @memberof NoteUpdate
     */
    content: string;
}

/**
 * Check if a given object implements the NoteUpdate interface.
 */
export function instanceOfNoteUpdate(value: object): value is NoteUpdate {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function NoteUpdateFromJSON(json: any): NoteUpdate {
    return NoteUpdateFromJSONTyped(json, false);
}

export function NoteUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function NoteUpdateToJSON(json: any): NoteUpdate {
    return NoteUpdateToJSONTyped(json, false);
}

export function NoteUpdateToJSONTyped(value?: NoteUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

