/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteCreate
 */
export interface NoteCreate {
    /**
     * 
     * @type {string}
     * @memberof NoteCreate
     */
    content: string;
}

/**
 * Check if a given object implements the NoteCreate interface.
 */
export function instanceOfNoteCreate(value: object): value is NoteCreate {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function NoteCreateFromJSON(json: any): NoteCreate {
    return NoteCreateFromJSONTyped(json, false);
}

export function NoteCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function NoteCreateToJSON(json: any): NoteCreate {
    return NoteCreateToJSONTyped(json, false);
}

export function NoteCreateToJSONTyped(value?: NoteCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

