/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionResponse
 */
export interface PermissionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PermissionResponse
     */
    canEdit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PermissionResponse
     */
    canDelete: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PermissionResponse
     */
    isOwner: boolean;
}

/**
 * Check if a given object implements the PermissionResponse interface.
 */
export function instanceOfPermissionResponse(value: object): value is PermissionResponse {
    if (!('canEdit' in value) || value['canEdit'] === undefined) return false;
    if (!('canDelete' in value) || value['canDelete'] === undefined) return false;
    if (!('isOwner' in value) || value['isOwner'] === undefined) return false;
    return true;
}

export function PermissionResponseFromJSON(json: any): PermissionResponse {
    return PermissionResponseFromJSONTyped(json, false);
}

export function PermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'canEdit': json['can_edit'],
        'canDelete': json['can_delete'],
        'isOwner': json['is_owner'],
    };
}

export function PermissionResponseToJSON(json: any): PermissionResponse {
    return PermissionResponseToJSONTyped(json, false);
}

export function PermissionResponseToJSONTyped(value?: PermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_edit': value['canEdit'],
        'can_delete': value['canDelete'],
        'is_owner': value['isOwner'],
    };
}

