/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request schema for publishing campaigns, stations, or sensors.
 * @export
 * @interface PublishRequest
 */
export interface PublishRequest {
    /**
     * If true, cascade publish to child resources (e.g., sensors when publishing station)
     * @type {boolean}
     * @memberof PublishRequest
     */
    cascade?: boolean;
    /**
     * If true, force publish even if already published
     * @type {boolean}
     * @memberof PublishRequest
     */
    force?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublishRequest
     */
    organization?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublishRequest
     */
    ckanDatasetName?: string | null;
    /**
     * If true, update an existing matching CKAN dataset instead of failing on name conflict
     * @type {boolean}
     * @memberof PublishRequest
     */
    patchExistingCkanDataset?: boolean;
}

/**
 * Check if a given object implements the PublishRequest interface.
 */
export function instanceOfPublishRequest(value: object): value is PublishRequest {
    return true;
}

export function PublishRequestFromJSON(json: any): PublishRequest {
    return PublishRequestFromJSONTyped(json, false);
}

export function PublishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cascade': json['cascade'] == null ? undefined : json['cascade'],
        'force': json['force'] == null ? undefined : json['force'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'ckanDatasetName': json['ckan_dataset_name'] == null ? undefined : json['ckan_dataset_name'],
        'patchExistingCkanDataset': json['patch_existing_ckan_dataset'] == null ? undefined : json['patch_existing_ckan_dataset'],
    };
}

export function PublishRequestToJSON(json: any): PublishRequest {
    return PublishRequestToJSONTyped(json, false);
}

export function PublishRequestToJSONTyped(value?: PublishRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cascade': value['cascade'],
        'force': value['force'],
        'organization': value['organization'],
        'ckan_dataset_name': value['ckanDatasetName'],
        'patch_existing_ckan_dataset': value['patchExistingCkanDataset'],
    };
}

