/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PublishRequest
 */
export interface PublishRequest {
    /**
     *
     * @type {boolean}
     * @memberof PublishRequest
     */
    cascade?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PublishRequest
     */
    force?: boolean;
}

/**
 * Check if a given object implements the PublishRequest interface.
 */
export function instanceOfPublishRequest(value: object): value is PublishRequest {
    return true;
}

export function PublishRequestFromJSON(json: any): PublishRequest {
    return PublishRequestFromJSONTyped(json, false);
}

export function PublishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishRequest {
    if (json == null) {
        return json;
    }
    return {

        'cascade': json['cascade'] == null ? undefined : json['cascade'],
        'force': json['force'] == null ? undefined : json['force'],
    };
}

export function PublishRequestToJSON(json: any): PublishRequest {
    return PublishRequestToJSONTyped(json, false);
}

export function PublishRequestToJSONTyped(value?: PublishRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'cascade': value['cascade'],
        'force': value['force'],
    };
}