/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PyTASPi
 */
export interface PyTASPi {
    /**
     * 
     * @type {number}
     * @memberof PyTASPi
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    institution: string;
    /**
     * 
     * @type {number}
     * @memberof PyTASPi
     */
    institutionId: number;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    department: string;
    /**
     * 
     * @type {number}
     * @memberof PyTASPi
     */
    departmentId: number;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    citizenship: string;
    /**
     * 
     * @type {number}
     * @memberof PyTASPi
     */
    citizenshipId: number;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof PyTASPi
     */
    uid: number;
    /**
     * 
     * @type {string}
     * @memberof PyTASPi
     */
    homeDirectory: string;
    /**
     * 
     * @type {number}
     * @memberof PyTASPi
     */
    gid: number;
}

/**
 * Check if a given object implements the PyTASPi interface.
 */
export function instanceOfPyTASPi(value: object): value is PyTASPi {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('institution' in value) || value['institution'] === undefined) return false;
    if (!('institutionId' in value) || value['institutionId'] === undefined) return false;
    if (!('department' in value) || value['department'] === undefined) return false;
    if (!('departmentId' in value) || value['departmentId'] === undefined) return false;
    if (!('citizenship' in value) || value['citizenship'] === undefined) return false;
    if (!('citizenshipId' in value) || value['citizenshipId'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('uid' in value) || value['uid'] === undefined) return false;
    if (!('homeDirectory' in value) || value['homeDirectory'] === undefined) return false;
    if (!('gid' in value) || value['gid'] === undefined) return false;
    return true;
}

export function PyTASPiFromJSON(json: any): PyTASPi {
    return PyTASPiFromJSONTyped(json, false);
}

export function PyTASPiFromJSONTyped(json: any, ignoreDiscriminator: boolean): PyTASPi {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'institution': json['institution'],
        'institutionId': json['institutionId'],
        'department': json['department'],
        'departmentId': json['departmentId'],
        'citizenship': json['citizenship'],
        'citizenshipId': json['citizenshipId'],
        'source': json['source'],
        'uid': json['uid'],
        'homeDirectory': json['homeDirectory'],
        'gid': json['gid'],
    };
}

export function PyTASPiToJSON(json: any): PyTASPi {
    return PyTASPiToJSONTyped(json, false);
}

export function PyTASPiToJSONTyped(value?: PyTASPi | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'institution': value['institution'],
        'institutionId': value['institutionId'],
        'department': value['department'],
        'departmentId': value['departmentId'],
        'citizenship': value['citizenship'],
        'citizenshipId': value['citizenshipId'],
        'source': value['source'],
        'uid': value['uid'],
        'homeDirectory': value['homeDirectory'],
        'gid': value['gid'],
    };
}

