/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorCreateResponse
 */
export interface SensorCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof SensorCreateResponse
     */
    id: number;
}

/**
 * Check if a given object implements the SensorCreateResponse interface.
 */
export function instanceOfSensorCreateResponse(value: object): value is SensorCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SensorCreateResponseFromJSON(json: any): SensorCreateResponse {
    return SensorCreateResponseFromJSONTyped(json, false);
}

export function SensorCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SensorCreateResponseToJSON(json: any): SensorCreateResponse {
    return SensorCreateResponseToJSONTyped(json, false);
}

export function SensorCreateResponseToJSONTyped(value?: SensorCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

