/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SortField = {
    Alias: 'alias',
    Description: 'description',
    Postprocess: 'postprocess',
    Postprocessscript: 'postprocessscript',
    Units: 'units',
    Variablename: 'variablename',
    MaxValue: 'max_value',
    MinValue: 'min_value',
    AvgValue: 'avg_value',
    StddevValue: 'stddev_value',
    Percentile90: 'percentile_90',
    Percentile95: 'percentile_95',
    Percentile99: 'percentile_99',
    Count: 'count',
    FirstMeasurementValue: 'first_measurement_value',
    FirstMeasurementCollectiontime: 'first_measurement_collectiontime',
    LastMeasurementValue: 'last_measurement_value',
    LastMeasurementCollectiontime: 'last_measurement_collectiontime'
} as const;
export type SortField = typeof SortField[keyof typeof SortField];


export function instanceOfSortField(value: any): boolean {
    for (const key in SortField) {
        if (Object.prototype.hasOwnProperty.call(SortField, key)) {
            if (SortField[key as keyof typeof SortField] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SortFieldFromJSON(json: any): SortField {
    return SortFieldFromJSONTyped(json, false);
}

export function SortFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortField {
    return json as SortField;
}

export function SortFieldToJSON(value?: SortField | null): any {
    return value as any;
}

export function SortFieldToJSONTyped(value: any, ignoreDiscriminator: boolean): SortField {
    return value as SortField;
}

