/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StationType = {
    Mobile: 'mobile',
    Static: 'static'
} as const;
export type StationType = typeof StationType[keyof typeof StationType];


export function instanceOfStationType(value: any): boolean {
    for (const key in StationType) {
        if (Object.prototype.hasOwnProperty.call(StationType, key)) {
            if (StationType[key as keyof typeof StationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StationTypeFromJSON(json: any): StationType {
    return StationTypeFromJSONTyped(json, false);
}

export function StationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationType {
    return json as StationType;
}

export function StationTypeToJSON(value?: StationType | null): any {
    return value as any;
}

export function StationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StationType {
    return value as StationType;
}

