/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StationType } from './StationType';
import {
    StationTypeFromJSON,
    StationTypeFromJSONTyped,
    StationTypeToJSON,
    StationTypeToJSONTyped,
} from './StationType';

/**
 * 
 * @export
 * @interface StationUpdate
 */
export interface StationUpdate {
    /**
     * 
     * @type {string}
     * @memberof StationUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StationUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StationUpdate
     */
    contactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StationUpdate
     */
    contactEmail?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StationUpdate
     */
    active?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof StationUpdate
     */
    startDate?: Date | null;
    /**
     * 
     * @type {StationType}
     * @memberof StationUpdate
     */
    stationType?: StationType | null;
}



/**
 * Check if a given object implements the StationUpdate interface.
 */
export function instanceOfStationUpdate(value: object): value is StationUpdate {
    return true;
}

export function StationUpdateFromJSON(json: any): StationUpdate {
    return StationUpdateFromJSONTyped(json, false);
}

export function StationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'contactName': json['contact_name'] == null ? undefined : json['contact_name'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'active': json['active'] == null ? undefined : json['active'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'stationType': json['station_type'] == null ? undefined : StationTypeFromJSON(json['station_type']),
    };
}

export function StationUpdateToJSON(json: any): StationUpdate {
    return StationUpdateToJSONTyped(json, false);
}

export function StationUpdateToJSONTyped(value?: StationUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'contact_name': value['contactName'],
        'contact_email': value['contactEmail'],
        'active': value['active'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'station_type': StationTypeToJSON(value['stationType']),
    };
}

