/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationCreateResponse
 */
export interface StationCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof StationCreateResponse
     */
    id: number;
}

/**
 * Check if a given object implements the StationCreateResponse interface.
 */
export function instanceOfStationCreateResponse(value: object): value is StationCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function StationCreateResponseFromJSON(json: any): StationCreateResponse {
    return StationCreateResponseFromJSONTyped(json, false);
}

export function StationCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function StationCreateResponseToJSON(json: any): StationCreateResponse {
    return StationCreateResponseToJSONTyped(json, false);
}

export function StationCreateResponseToJSONTyped(value?: StationCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

