"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSummaryListCampaigns = instanceOfSummaryListCampaigns;
exports.SummaryListCampaignsFromJSON = SummaryListCampaignsFromJSON;
exports.SummaryListCampaignsFromJSONTyped = SummaryListCampaignsFromJSONTyped;
exports.SummaryListCampaignsToJSON = SummaryListCampaignsToJSON;
exports.SummaryListCampaignsToJSONTyped = SummaryListCampaignsToJSONTyped;
/**
 * Check if a given object implements the SummaryListCampaigns interface.
 */
function instanceOfSummaryListCampaigns(value) {
    return true;
}
function SummaryListCampaignsFromJSON(json) {
    return SummaryListCampaignsFromJSONTyped(json, false);
}
function SummaryListCampaignsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'sensorTypes': json['sensor_types'] == null ? undefined : json['sensor_types'],
        'variableNames': json['variable_names'] == null ? undefined : json['variable_names'],
    };
}
function SummaryListCampaignsToJSON(json) {
    return SummaryListCampaignsToJSONTyped(json, false);
}
function SummaryListCampaignsToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'sensor_types': value['sensorTypes'],
        'variable_names': value['variableNames'],
    };
}
