"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSummaryGetCampaign = instanceOfSummaryGetCampaign;
exports.SummaryGetCampaignFromJSON = SummaryGetCampaignFromJSON;
exports.SummaryGetCampaignFromJSONTyped = SummaryGetCampaignFromJSONTyped;
exports.SummaryGetCampaignToJSON = SummaryGetCampaignToJSON;
exports.SummaryGetCampaignToJSONTyped = SummaryGetCampaignToJSONTyped;
/**
 * Check if a given object implements the SummaryGetCampaign interface.
 */
function instanceOfSummaryGetCampaign(value) {
    if (!('stationCount' in value) || value['stationCount'] === undefined)
        return false;
    if (!('sensorCount' in value) || value['sensorCount'] === undefined)
        return false;
    if (!('sensorTypes' in value) || value['sensorTypes'] === undefined)
        return false;
    if (!('sensorVariables' in value) || value['sensorVariables'] === undefined)
        return false;
    return true;
}
function SummaryGetCampaignFromJSON(json) {
    return SummaryGetCampaignFromJSONTyped(json, false);
}
function SummaryGetCampaignFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'stationCount': json['station_count'],
        'sensorCount': json['sensor_count'],
        'sensorTypes': json['sensor_types'],
        'sensorVariables': json['sensor_variables'],
    };
}
function SummaryGetCampaignToJSON(json) {
    return SummaryGetCampaignToJSONTyped(json, false);
}
function SummaryGetCampaignToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'station_count': value['stationCount'],
        'sensor_count': value['sensorCount'],
        'sensor_types': value['sensorTypes'],
        'sensor_variables': value['sensorVariables'],
    };
}
