/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SummaryGetCampaign
 */
export interface SummaryGetCampaign {
    /**
     * 
     * @type {number}
     * @memberof SummaryGetCampaign
     */
    stationCount: number;
    /**
     * 
     * @type {number}
     * @memberof SummaryGetCampaign
     */
    sensorCount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SummaryGetCampaign
     */
    sensorTypes: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SummaryGetCampaign
     */
    sensorVariables: Array<string>;
}

/**
 * Check if a given object implements the SummaryGetCampaign interface.
 */
export function instanceOfSummaryGetCampaign(value: object): value is SummaryGetCampaign {
    if (!('stationCount' in value) || value['stationCount'] === undefined) return false;
    if (!('sensorCount' in value) || value['sensorCount'] === undefined) return false;
    if (!('sensorTypes' in value) || value['sensorTypes'] === undefined) return false;
    if (!('sensorVariables' in value) || value['sensorVariables'] === undefined) return false;
    return true;
}

export function SummaryGetCampaignFromJSON(json: any): SummaryGetCampaign {
    return SummaryGetCampaignFromJSONTyped(json, false);
}

export function SummaryGetCampaignFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryGetCampaign {
    if (json == null) {
        return json;
    }
    return {
        
        'stationCount': json['station_count'],
        'sensorCount': json['sensor_count'],
        'sensorTypes': json['sensor_types'],
        'sensorVariables': json['sensor_variables'],
    };
}

export function SummaryGetCampaignToJSON(json: any): SummaryGetCampaign {
    return SummaryGetCampaignToJSONTyped(json, false);
}

export function SummaryGetCampaignToJSONTyped(value?: SummaryGetCampaign | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'station_count': value['stationCount'],
        'sensor_count': value['sensorCount'],
        'sensor_types': value['sensorTypes'],
        'sensor_variables': value['sensorVariables'],
    };
}

