/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SummaryListCampaigns
 */
export interface SummaryListCampaigns {
    /**
     * 
     * @type {Array<string>}
     * @memberof SummaryListCampaigns
     */
    sensorTypes?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SummaryListCampaigns
     */
    variableNames?: Array<string> | null;
}

/**
 * Check if a given object implements the SummaryListCampaigns interface.
 */
export function instanceOfSummaryListCampaigns(value: object): value is SummaryListCampaigns {
    return true;
}

export function SummaryListCampaignsFromJSON(json: any): SummaryListCampaigns {
    return SummaryListCampaignsFromJSONTyped(json, false);
}

export function SummaryListCampaignsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryListCampaigns {
    if (json == null) {
        return json;
    }
    return {
        
        'sensorTypes': json['sensor_types'] == null ? undefined : json['sensor_types'],
        'variableNames': json['variable_names'] == null ? undefined : json['variable_names'],
    };
}

export function SummaryListCampaignsToJSON(json: any): SummaryListCampaigns {
    return SummaryListCampaignsToJSONTyped(json, false);
}

export function SummaryListCampaignsToJSONTyped(value?: SummaryListCampaigns | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sensor_types': value['sensorTypes'],
        'variable_names': value['variableNames'],
    };
}

