/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSensorStatisticsResponse
 */
export interface UpdateSensorStatisticsResponse {
    /**
     * 
     * @type {number}
     * @memberof UpdateSensorStatisticsResponse
     */
    sensorId: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSensorStatisticsResponse
     */
    updated: boolean;
}

/**
 * Check if a given object implements the UpdateSensorStatisticsResponse interface.
 */
export function instanceOfUpdateSensorStatisticsResponse(value: object): value is UpdateSensorStatisticsResponse {
    if (!('sensorId' in value) || value['sensorId'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function UpdateSensorStatisticsResponseFromJSON(json: any): UpdateSensorStatisticsResponse {
    return UpdateSensorStatisticsResponseFromJSONTyped(json, false);
}

export function UpdateSensorStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSensorStatisticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sensorId': json['sensor_id'],
        'updated': json['updated'],
    };
}

export function UpdateSensorStatisticsResponseToJSON(json: any): UpdateSensorStatisticsResponse {
    return UpdateSensorStatisticsResponseToJSONTyped(json, false);
}

export function UpdateSensorStatisticsResponseToJSONTyped(value?: UpdateSensorStatisticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sensor_id': value['sensorId'],
        'updated': value['updated'],
    };
}

