/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * State of once-per-upload post-processing (statistics/geometry).
 * @export
 * @interface UploadPostProcessing
 */
export interface UploadPostProcessing {
    /**
     * 
     * @type {string}
     * @memberof UploadPostProcessing
     */
    status: string;
    /**
     * 
     * @type {boolean}
     * @memberof UploadPostProcessing
     */
    statisticsRefreshed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UploadPostProcessing
     */
    stationGeometryRefreshed?: boolean;
}

/**
 * Check if a given object implements the UploadPostProcessing interface.
 */
export function instanceOfUploadPostProcessing(value: object): value is UploadPostProcessing {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UploadPostProcessingFromJSON(json: any): UploadPostProcessing {
    return UploadPostProcessingFromJSONTyped(json, false);
}

export function UploadPostProcessingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadPostProcessing {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'statisticsRefreshed': json['statistics_refreshed'] == null ? undefined : json['statistics_refreshed'],
        'stationGeometryRefreshed': json['station_geometry_refreshed'] == null ? undefined : json['station_geometry_refreshed'],
    };
}

export function UploadPostProcessingToJSON(json: any): UploadPostProcessing {
    return UploadPostProcessingToJSONTyped(json, false);
}

export function UploadPostProcessingToJSONTyped(value?: UploadPostProcessing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'statistics_refreshed': value['statisticsRefreshed'],
        'station_geometry_refreshed': value['stationGeometryRefreshed'],
    };
}

