/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Per-chunk measurement ingestion counts returned by a CSV upload.
 * @export
 * @interface UploadAudit
 */
export interface UploadAudit {
    /**
     * 
     * @type {number}
     * @memberof UploadAudit
     */
    measurementRowsRead: number;
    /**
     * 
     * @type {number}
     * @memberof UploadAudit
     */
    measurementValuesAttempted: number;
    /**
     * 
     * @type {number}
     * @memberof UploadAudit
     */
    measurementValuesInserted: number;
    /**
     * 
     * @type {number}
     * @memberof UploadAudit
     */
    measurementValuesSkippedDuplicate: number;
    /**
     * 
     * @type {number}
     * @memberof UploadAudit
     */
    sensorAliasCount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UploadAudit
     */
    rowErrors?: Array<string>;
}

/**
 * Check if a given object implements the UploadAudit interface.
 */
export function instanceOfUploadAudit(value: object): value is UploadAudit {
    if (!('measurementRowsRead' in value) || value['measurementRowsRead'] === undefined) return false;
    if (!('measurementValuesAttempted' in value) || value['measurementValuesAttempted'] === undefined) return false;
    if (!('measurementValuesInserted' in value) || value['measurementValuesInserted'] === undefined) return false;
    if (!('measurementValuesSkippedDuplicate' in value) || value['measurementValuesSkippedDuplicate'] === undefined) return false;
    if (!('sensorAliasCount' in value) || value['sensorAliasCount'] === undefined) return false;
    return true;
}

export function UploadAuditFromJSON(json: any): UploadAudit {
    return UploadAuditFromJSONTyped(json, false);
}

export function UploadAuditFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadAudit {
    if (json == null) {
        return json;
    }
    return {
        
        'measurementRowsRead': json['measurement_rows_read'],
        'measurementValuesAttempted': json['measurement_values_attempted'],
        'measurementValuesInserted': json['measurement_values_inserted'],
        'measurementValuesSkippedDuplicate': json['measurement_values_skipped_duplicate'],
        'sensorAliasCount': json['sensor_alias_count'],
        'rowErrors': json['row_errors'] == null ? undefined : json['row_errors'],
    };
}

export function UploadAuditToJSON(json: any): UploadAudit {
    return UploadAuditToJSONTyped(json, false);
}

export function UploadAuditToJSONTyped(value?: UploadAudit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'measurement_rows_read': value['measurementRowsRead'],
        'measurement_values_attempted': value['measurementValuesAttempted'],
        'measurement_values_inserted': value['measurementValuesInserted'],
        'measurement_values_skipped_duplicate': value['measurementValuesSkippedDuplicate'],
        'sensor_alias_count': value['sensorAliasCount'],
        'row_errors': value['rowErrors'],
    };
}

