/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadAudit } from './UploadAudit';
import {
    UploadAuditFromJSON,
    UploadAuditFromJSONTyped,
    UploadAuditToJSON,
    UploadAuditToJSONTyped,
} from './UploadAudit';
import type { UploadCkanSync } from './UploadCkanSync';
import {
    UploadCkanSyncFromJSON,
    UploadCkanSyncFromJSONTyped,
    UploadCkanSyncToJSON,
    UploadCkanSyncToJSONTyped,
} from './UploadCkanSync';
import type { UploadPostProcessing } from './UploadPostProcessing';
import {
    UploadPostProcessingFromJSON,
    UploadPostProcessingFromJSONTyped,
    UploadPostProcessingToJSON,
    UploadPostProcessingToJSONTyped,
} from './UploadPostProcessing';

/**
 * Response for a CSV upload request.
 * 
 * New structured fields (``audit``, ``post_processing``, ``ckan_sync``,
 * ``finalized``) are added alongside the legacy response keys that existing
 * clients depend on.
 * @export
 * @interface UploadFileCsvResponse
 */
export interface UploadFileCsvResponse {
    /**
     * 
     * @type {number}
     * @memberof UploadFileCsvResponse
     */
    uploadEventId: number;
    /**
     * 
     * @type {string}
     * @memberof UploadFileCsvResponse
     */
    uploadSessionId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UploadFileCsvResponse
     */
    finalized: boolean;
    /**
     * 
     * @type {number}
     * @memberof UploadFileCsvResponse
     */
    chunkIndex?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UploadFileCsvResponse
     */
    totalChunks?: number | null;
    /**
     * 
     * @type {UploadAudit}
     * @memberof UploadFileCsvResponse
     */
    audit: UploadAudit;
    /**
     * 
     * @type {UploadPostProcessing}
     * @memberof UploadFileCsvResponse
     */
    postProcessing: UploadPostProcessing;
    /**
     * 
     * @type {UploadCkanSync}
     * @memberof UploadFileCsvResponse
     */
    ckanSync: UploadCkanSync;
    /**
     * 
     * @type {boolean}
     * @memberof UploadFileCsvResponse
     */
    uploadedFileSensorsStoredInMemory: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UploadFileCsvResponse
     */
    uploadedFileMeasurementsStoredInMemory: boolean;
    /**
     * 
     * @type {number}
     * @memberof UploadFileCsvResponse
     */
    totalSensorsProcessed: number;
    /**
     * 
     * @type {number}
     * @memberof UploadFileCsvResponse
     */
    totalMeasurementsAddedToDatabase: number;
    /**
     * 
     * @type {string}
     * @memberof UploadFileCsvResponse
     */
    dataProcessingTime: string;
    /**
     * 
     * @type {Array<Error>}
     * @memberof UploadFileCsvResponse
     */
    errors?: Array<Error>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UploadFileCsvResponse
     */
    ckanWarnings?: Array<string> | null;
}

/**
 * Check if a given object implements the UploadFileCsvResponse interface.
 */
export function instanceOfUploadFileCsvResponse(value: object): value is UploadFileCsvResponse {
    if (!('uploadEventId' in value) || value['uploadEventId'] === undefined) return false;
    if (!('finalized' in value) || value['finalized'] === undefined) return false;
    if (!('audit' in value) || value['audit'] === undefined) return false;
    if (!('postProcessing' in value) || value['postProcessing'] === undefined) return false;
    if (!('ckanSync' in value) || value['ckanSync'] === undefined) return false;
    if (!('uploadedFileSensorsStoredInMemory' in value) || value['uploadedFileSensorsStoredInMemory'] === undefined) return false;
    if (!('uploadedFileMeasurementsStoredInMemory' in value) || value['uploadedFileMeasurementsStoredInMemory'] === undefined) return false;
    if (!('totalSensorsProcessed' in value) || value['totalSensorsProcessed'] === undefined) return false;
    if (!('totalMeasurementsAddedToDatabase' in value) || value['totalMeasurementsAddedToDatabase'] === undefined) return false;
    if (!('dataProcessingTime' in value) || value['dataProcessingTime'] === undefined) return false;
    return true;
}

export function UploadFileCsvResponseFromJSON(json: any): UploadFileCsvResponse {
    return UploadFileCsvResponseFromJSONTyped(json, false);
}

export function UploadFileCsvResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileCsvResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadEventId': json['upload_event_id'],
        'uploadSessionId': json['upload_session_id'] == null ? undefined : json['upload_session_id'],
        'finalized': json['finalized'],
        'chunkIndex': json['chunk_index'] == null ? undefined : json['chunk_index'],
        'totalChunks': json['total_chunks'] == null ? undefined : json['total_chunks'],
        'audit': UploadAuditFromJSON(json['audit']),
        'postProcessing': UploadPostProcessingFromJSON(json['post_processing']),
        'ckanSync': UploadCkanSyncFromJSON(json['ckan_sync']),
        'uploadedFileSensorsStoredInMemory': json['uploaded_file_sensors stored in memory'],
        'uploadedFileMeasurementsStoredInMemory': json['uploaded_file_measurements stored in memory'],
        'totalSensorsProcessed': json['Total sensors processed'],
        'totalMeasurementsAddedToDatabase': json['Total measurements added to database'],
        'dataProcessingTime': json['Data Processing time'],
        'errors': json['errors'] == null ? undefined : json['errors'],
        'ckanWarnings': json['ckan_warnings'] == null ? undefined : json['ckan_warnings'],
    };
}

export function UploadFileCsvResponseToJSON(json: any): UploadFileCsvResponse {
    return UploadFileCsvResponseToJSONTyped(json, false);
}

export function UploadFileCsvResponseToJSONTyped(value?: UploadFileCsvResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'upload_event_id': value['uploadEventId'],
        'upload_session_id': value['uploadSessionId'],
        'finalized': value['finalized'],
        'chunk_index': value['chunkIndex'],
        'total_chunks': value['totalChunks'],
        'audit': UploadAuditToJSON(value['audit']),
        'post_processing': UploadPostProcessingToJSON(value['postProcessing']),
        'ckan_sync': UploadCkanSyncToJSON(value['ckanSync']),
        'uploaded_file_sensors stored in memory': value['uploadedFileSensorsStoredInMemory'],
        'uploaded_file_measurements stored in memory': value['uploadedFileMeasurementsStoredInMemory'],
        'Total sensors processed': value['totalSensorsProcessed'],
        'Total measurements added to database': value['totalMeasurementsAddedToDatabase'],
        'Data Processing time': value['dataProcessingTime'],
        'errors': value['errors'],
        'ckan_warnings': value['ckanWarnings'],
    };
}

