/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: wmobley@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * State of the deferred CKAN dataset/resource synchronization.
 * @export
 * @interface UploadCkanSync
 */
export interface UploadCkanSync {
    /**
     * 
     * @type {string}
     * @memberof UploadCkanSync
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UploadCkanSync
     */
    message?: string | null;
}

/**
 * Check if a given object implements the UploadCkanSync interface.
 */
export function instanceOfUploadCkanSync(value: object): value is UploadCkanSync {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UploadCkanSyncFromJSON(json: any): UploadCkanSync {
    return UploadCkanSyncFromJSONTyped(json, false);
}

export function UploadCkanSyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadCkanSync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UploadCkanSyncToJSON(json: any): UploadCkanSync {
    return UploadCkanSyncToJSONTyped(json, false);
}

export function UploadCkanSyncToJSONTyped(value?: UploadCkanSync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

