/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRole } from './UserRole';
import {
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
    UserRoleToJSONTyped,
} from './UserRole';

/**
 * 
 * @export
 * @interface UserRoleResponse
 */
export interface UserRoleResponse {
    /**
     * 
     * @type {string}
     * @memberof UserRoleResponse
     */
    username: string;
    /**
     * 
     * @type {UserRole}
     * @memberof UserRoleResponse
     */
    role: UserRole;
}



/**
 * Check if a given object implements the UserRoleResponse interface.
 */
export function instanceOfUserRoleResponse(value: object): value is UserRoleResponse {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserRoleResponseFromJSON(json: any): UserRoleResponse {
    return UserRoleResponseFromJSONTyped(json, false);
}

export function UserRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'role': UserRoleFromJSON(json['role']),
    };
}

export function UserRoleResponseToJSON(json: any): UserRoleResponse {
    return UserRoleResponseToJSONTyped(json, false);
}

export function UserRoleResponseToJSONTyped(value?: UserRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'role': UserRoleToJSON(value['role']),
    };
}

