/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRole } from './UserRole';
import {
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
    UserRoleToJSONTyped,
} from './UserRole';

/**
 * 
 * @export
 * @interface UserRoleUpdate
 */
export interface UserRoleUpdate {
    /**
     * 
     * @type {UserRole}
     * @memberof UserRoleUpdate
     */
    role: UserRole;
}



/**
 * Check if a given object implements the UserRoleUpdate interface.
 */
export function instanceOfUserRoleUpdate(value: object): value is UserRoleUpdate {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserRoleUpdateFromJSON(json: any): UserRoleUpdate {
    return UserRoleUpdateFromJSONTyped(json, false);
}

export function UserRoleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'role': UserRoleFromJSON(json['role']),
    };
}

export function UserRoleUpdateToJSON(json: any): UserRoleUpdate {
    return UserRoleUpdateToJSONTyped(json, false);
}

export function UserRoleUpdateToJSONTyped(value?: UserRoleUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': UserRoleToJSON(value['role']),
    };
}

