"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfValidationErrorLocInner = instanceOfValidationErrorLocInner;
exports.ValidationErrorLocInnerFromJSON = ValidationErrorLocInnerFromJSON;
exports.ValidationErrorLocInnerFromJSONTyped = ValidationErrorLocInnerFromJSONTyped;
exports.ValidationErrorLocInnerToJSON = ValidationErrorLocInnerToJSON;
exports.ValidationErrorLocInnerToJSONTyped = ValidationErrorLocInnerToJSONTyped;
/**
 * Check if a given object implements the ValidationErrorLocInner interface.
 */
function instanceOfValidationErrorLocInner(value) {
    return true;
}
function ValidationErrorLocInnerFromJSON(json) {
    return ValidationErrorLocInnerFromJSONTyped(json, false);
}
function ValidationErrorLocInnerFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ValidationErrorLocInnerToJSON(json) {
    return ValidationErrorLocInnerToJSONTyped(json, false);
}
function ValidationErrorLocInnerToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    return value;
}
