/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CampaignPagination,
  GetCampaignResponse,
  HTTPValidationError,
} from '../models/index';
import {
    CampaignPaginationFromJSON,
    CampaignPaginationToJSON,
    GetCampaignResponseFromJSON,
    GetCampaignResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetCampaignApiV1CampaignsCampaignIdGetRequest {
    campaignId: number;
}

export interface ListCampaignsApiV1CampaignsGetRequest {
    page?: number;
    limit?: number;
    bbox?: string;
    startDate?: Date | null;
    endDate?: Date | null;
}

/**
 * 
 */
export class CampaignsApi extends runtime.BaseAPI {

    /**
     * Get Campaign
     */
    async getCampaignApiV1CampaignsCampaignIdGetRaw(requestParameters: GetCampaignApiV1CampaignsCampaignIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCampaignResponse>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling getCampaignApiV1CampaignsCampaignIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCampaignResponseFromJSON(jsonValue));
    }

    /**
     * Get Campaign
     */
    async getCampaignApiV1CampaignsCampaignIdGet(requestParameters: GetCampaignApiV1CampaignsCampaignIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCampaignResponse> {
        const response = await this.getCampaignApiV1CampaignsCampaignIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Campaigns
     */
    async listCampaignsApiV1CampaignsGetRaw(requestParameters: ListCampaignsApiV1CampaignsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CampaignPagination>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString();
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/campaigns`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CampaignPaginationFromJSON(jsonValue));
    }

    /**
     * List Campaigns
     */
    async listCampaignsApiV1CampaignsGet(requestParameters: ListCampaignsApiV1CampaignsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CampaignPagination> {
        const response = await this.listCampaignsApiV1CampaignsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
