/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DebugCkanAuthApiV1CkanDebugAuthGetRequest {
    xTAPISTOKEN?: string | null;
    authorization?: string | null;
}

export interface ListUserOrganizationsApiV1CkanOrganizationsGetRequest {
    xTAPISTOKEN?: string | null;
    authorization?: string | null;
}

/**
 * 
 */
export class CkanApi extends runtime.BaseAPI {

    /**
     * Debug Ckan Auth
     */
    async debugCkanAuthApiV1CkanDebugAuthGetRaw(requestParameters: DebugCkanAuthApiV1CkanDebugAuthGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTAPISTOKEN'] != null) {
            headerParameters['X-TAPIS-TOKEN'] = String(requestParameters['xTAPISTOKEN']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/ckan/debug/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Debug Ckan Auth
     */
    async debugCkanAuthApiV1CkanDebugAuthGet(requestParameters: DebugCkanAuthApiV1CkanDebugAuthGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.debugCkanAuthApiV1CkanDebugAuthGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List User Organizations
     */
    async listUserOrganizationsApiV1CkanOrganizationsGetRaw(requestParameters: ListUserOrganizationsApiV1CkanOrganizationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTAPISTOKEN'] != null) {
            headerParameters['X-TAPIS-TOKEN'] = String(requestParameters['xTAPISTOKEN']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/ckan/organizations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List User Organizations
     */
    async listUserOrganizationsApiV1CkanOrganizationsGet(requestParameters: ListUserOrganizationsApiV1CkanOrganizationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.listUserOrganizationsApiV1CkanOrganizationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
