/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MetadataSchemaCreate,
  MetadataSchemaListResponse,
  MetadataSchemaResponse,
  MetadataSchemaUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MetadataSchemaCreateFromJSON,
    MetadataSchemaCreateToJSON,
    MetadataSchemaListResponseFromJSON,
    MetadataSchemaListResponseToJSON,
    MetadataSchemaResponseFromJSON,
    MetadataSchemaResponseToJSON,
    MetadataSchemaUpdateFromJSON,
    MetadataSchemaUpdateToJSON,
} from '../models/index';

export interface CreateMetadataSchemaApiV1MetadataSchemaPostRequest {
    metadataSchemaCreate: MetadataSchemaCreate;
}

export interface DeleteMetadataSchemaApiV1MetadataSchemaSchemaIdDeleteRequest {
    schemaId: number;
}

export interface GetMetadataSchemaApiV1MetadataSchemaSchemaIdGetRequest {
    schemaId: number;
}

export interface ListMetadataSchemaApiV1MetadataSchemaGetRequest {
    scope?: string | null;
    activeOnly?: boolean;
}

export interface UpdateMetadataSchemaApiV1MetadataSchemaSchemaIdPatchRequest {
    schemaId: number;
    metadataSchemaUpdate: MetadataSchemaUpdate;
}

/**
 * 
 */
export class MetadataSchemaApi extends runtime.BaseAPI {

    /**
     * Create Metadata Schema
     */
    async createMetadataSchemaApiV1MetadataSchemaPostRaw(requestParameters: CreateMetadataSchemaApiV1MetadataSchemaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataSchemaResponse>> {
        if (requestParameters['metadataSchemaCreate'] == null) {
            throw new runtime.RequiredError(
                'metadataSchemaCreate',
                'Required parameter "metadataSchemaCreate" was null or undefined when calling createMetadataSchemaApiV1MetadataSchemaPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/metadata-schema`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataSchemaCreateToJSON(requestParameters['metadataSchemaCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataSchemaResponseFromJSON(jsonValue));
    }

    /**
     * Create Metadata Schema
     */
    async createMetadataSchemaApiV1MetadataSchemaPost(requestParameters: CreateMetadataSchemaApiV1MetadataSchemaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataSchemaResponse> {
        const response = await this.createMetadataSchemaApiV1MetadataSchemaPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Metadata Schema
     */
    async deleteMetadataSchemaApiV1MetadataSchemaSchemaIdDeleteRaw(requestParameters: DeleteMetadataSchemaApiV1MetadataSchemaSchemaIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['schemaId'] == null) {
            throw new runtime.RequiredError(
                'schemaId',
                'Required parameter "schemaId" was null or undefined when calling deleteMetadataSchemaApiV1MetadataSchemaSchemaIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/metadata-schema/{schema_id}`;
        urlPath = urlPath.replace(`{${"schema_id"}}`, encodeURIComponent(String(requestParameters['schemaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Metadata Schema
     */
    async deleteMetadataSchemaApiV1MetadataSchemaSchemaIdDelete(requestParameters: DeleteMetadataSchemaApiV1MetadataSchemaSchemaIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMetadataSchemaApiV1MetadataSchemaSchemaIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Metadata Schema
     */
    async getMetadataSchemaApiV1MetadataSchemaSchemaIdGetRaw(requestParameters: GetMetadataSchemaApiV1MetadataSchemaSchemaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataSchemaResponse>> {
        if (requestParameters['schemaId'] == null) {
            throw new runtime.RequiredError(
                'schemaId',
                'Required parameter "schemaId" was null or undefined when calling getMetadataSchemaApiV1MetadataSchemaSchemaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/metadata-schema/{schema_id}`;
        urlPath = urlPath.replace(`{${"schema_id"}}`, encodeURIComponent(String(requestParameters['schemaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataSchemaResponseFromJSON(jsonValue));
    }

    /**
     * Get Metadata Schema
     */
    async getMetadataSchemaApiV1MetadataSchemaSchemaIdGet(requestParameters: GetMetadataSchemaApiV1MetadataSchemaSchemaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataSchemaResponse> {
        const response = await this.getMetadataSchemaApiV1MetadataSchemaSchemaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Metadata Schema
     */
    async listMetadataSchemaApiV1MetadataSchemaGetRaw(requestParameters: ListMetadataSchemaApiV1MetadataSchemaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataSchemaListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['activeOnly'] != null) {
            queryParameters['active_only'] = requestParameters['activeOnly'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/metadata-schema`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataSchemaListResponseFromJSON(jsonValue));
    }

    /**
     * List Metadata Schema
     */
    async listMetadataSchemaApiV1MetadataSchemaGet(requestParameters: ListMetadataSchemaApiV1MetadataSchemaGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataSchemaListResponse> {
        const response = await this.listMetadataSchemaApiV1MetadataSchemaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Metadata Schema
     */
    async updateMetadataSchemaApiV1MetadataSchemaSchemaIdPatchRaw(requestParameters: UpdateMetadataSchemaApiV1MetadataSchemaSchemaIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataSchemaResponse>> {
        if (requestParameters['schemaId'] == null) {
            throw new runtime.RequiredError(
                'schemaId',
                'Required parameter "schemaId" was null or undefined when calling updateMetadataSchemaApiV1MetadataSchemaSchemaIdPatch().'
            );
        }

        if (requestParameters['metadataSchemaUpdate'] == null) {
            throw new runtime.RequiredError(
                'metadataSchemaUpdate',
                'Required parameter "metadataSchemaUpdate" was null or undefined when calling updateMetadataSchemaApiV1MetadataSchemaSchemaIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/metadata-schema/{schema_id}`;
        urlPath = urlPath.replace(`{${"schema_id"}}`, encodeURIComponent(String(requestParameters['schemaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataSchemaUpdateToJSON(requestParameters['metadataSchemaUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataSchemaResponseFromJSON(jsonValue));
    }

    /**
     * Update Metadata Schema
     */
    async updateMetadataSchemaApiV1MetadataSchemaSchemaIdPatch(requestParameters: UpdateMetadataSchemaApiV1MetadataSchemaSchemaIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataSchemaResponse> {
        const response = await this.updateMetadataSchemaApiV1MetadataSchemaSchemaIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
