/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BundleRequest,
  HTTPValidationError,
} from '../models/index';
import {
    BundleRequestFromJSON,
    BundleRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreatePodBundleApiV1PodsBundlePostRequest {
    bundleRequest: BundleRequest;
    xTAPISTOKEN?: string | null;
    authorization?: string | null;
}

/**
 * 
 */
export class PodsApi extends runtime.BaseAPI {

    /**
     * Create a Postgres/API/UI pod bundle using server-side credentials.
     * Create Pod Bundle
     */
    async createPodBundleApiV1PodsBundlePostRaw(requestParameters: CreatePodBundleApiV1PodsBundlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['bundleRequest'] == null) {
            throw new runtime.RequiredError(
                'bundleRequest',
                'Required parameter "bundleRequest" was null or undefined when calling createPodBundleApiV1PodsBundlePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTAPISTOKEN'] != null) {
            headerParameters['X-TAPIS-TOKEN'] = String(requestParameters['xTAPISTOKEN']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/pods/bundle`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BundleRequestToJSON(requestParameters['bundleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a Postgres/API/UI pod bundle using server-side credentials.
     * Create Pod Bundle
     */
    async createPodBundleApiV1PodsBundlePost(requestParameters: CreatePodBundleApiV1PodsBundlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createPodBundleApiV1PodsBundlePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
