/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetStationResponse,
  HTTPValidationError,
  ListStationsResponsePagination,
  StationCreate,
  StationCreateResponse,
} from '../models/index';
import {
    GetStationResponseFromJSON,
    GetStationResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListStationsResponsePaginationFromJSON,
    ListStationsResponsePaginationToJSON,
    StationCreateFromJSON,
    StationCreateToJSON,
    StationCreateResponseFromJSON,
    StationCreateResponseToJSON,
} from '../models/index';

export interface CreateStationApiV1CampaignsCampaignIdStationsPostRequest {
    campaignId: number;
    stationCreate: StationCreate;
}

export interface GetStationApiV1CampaignsCampaignIdStationsStationIdGetRequest {
    stationId: number;
    campaignId: number;
}

export interface ListStationsApiV1CampaignsCampaignIdStationsGetRequest {
    campaignId: number;
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class StationsApi extends runtime.BaseAPI {

    /**
     * Create Station
     */
    async createStationApiV1CampaignsCampaignIdStationsPostRaw(requestParameters: CreateStationApiV1CampaignsCampaignIdStationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StationCreateResponse>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling createStationApiV1CampaignsCampaignIdStationsPost().'
            );
        }

        if (requestParameters['stationCreate'] == null) {
            throw new runtime.RequiredError(
                'stationCreate',
                'Required parameter "stationCreate" was null or undefined when calling createStationApiV1CampaignsCampaignIdStationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}/stations`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StationCreateToJSON(requestParameters['stationCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StationCreateResponseFromJSON(jsonValue));
    }

    /**
     * Create Station
     */
    async createStationApiV1CampaignsCampaignIdStationsPost(requestParameters: CreateStationApiV1CampaignsCampaignIdStationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StationCreateResponse> {
        const response = await this.createStationApiV1CampaignsCampaignIdStationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Station
     */
    async getStationApiV1CampaignsCampaignIdStationsStationIdGetRaw(requestParameters: GetStationApiV1CampaignsCampaignIdStationsStationIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStationResponse>> {
        if (requestParameters['stationId'] == null) {
            throw new runtime.RequiredError(
                'stationId',
                'Required parameter "stationId" was null or undefined when calling getStationApiV1CampaignsCampaignIdStationsStationIdGet().'
            );
        }

        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling getStationApiV1CampaignsCampaignIdStationsStationIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}/stations/{station_id}`.replace(`{${"station_id"}}`, encodeURIComponent(String(requestParameters['stationId']))).replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStationResponseFromJSON(jsonValue));
    }

    /**
     * Get Station
     */
    async getStationApiV1CampaignsCampaignIdStationsStationIdGet(requestParameters: GetStationApiV1CampaignsCampaignIdStationsStationIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStationResponse> {
        const response = await this.getStationApiV1CampaignsCampaignIdStationsStationIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Stations
     */
    async listStationsApiV1CampaignsCampaignIdStationsGetRaw(requestParameters: ListStationsApiV1CampaignsCampaignIdStationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListStationsResponsePagination>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling listStationsApiV1CampaignsCampaignIdStationsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}/stations`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListStationsResponsePaginationFromJSON(jsonValue));
    }

    /**
     * List Stations
     */
    async listStationsApiV1CampaignsCampaignIdStationsGet(requestParameters: ListStationsApiV1CampaignsCampaignIdStationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListStationsResponsePagination> {
        const response = await this.listStationsApiV1CampaignsCampaignIdStationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
