/* tslint:disable */
/* eslint-disable */
/**
 * Upstream Sensor Storage
 * Sensor Storage for Upstream data
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  UserRoleResponse,
  UserRoleUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UserRoleResponseFromJSON,
    UserRoleResponseToJSON,
    UserRoleUpdateFromJSON,
    UserRoleUpdateToJSON,
} from '../models/index';

export interface DeleteUserRoleApiV1UserRolesUsernameDeleteRequest {
    username: string;
}

export interface UpsertUserRoleApiV1UserRolesUsernamePutRequest {
    username: string;
    userRoleUpdate: UserRoleUpdate;
}

/**
 * 
 */
export class UserRolesApi extends runtime.BaseAPI {

    /**
     * Delete User Role
     */
    async deleteUserRoleApiV1UserRolesUsernameDeleteRaw(requestParameters: DeleteUserRoleApiV1UserRolesUsernameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling deleteUserRoleApiV1UserRolesUsernameDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-roles/{username}`;
        urlPath = urlPath.replace(`{${"username"}}`, encodeURIComponent(String(requestParameters['username'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete User Role
     */
    async deleteUserRoleApiV1UserRolesUsernameDelete(requestParameters: DeleteUserRoleApiV1UserRolesUsernameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserRoleApiV1UserRolesUsernameDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * List User Roles
     */
    async listUserRolesApiV1UserRolesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserRoleResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-roles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserRoleResponseFromJSON));
    }

    /**
     * List User Roles
     */
    async listUserRolesApiV1UserRolesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserRoleResponse>> {
        const response = await this.listUserRolesApiV1UserRolesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Upsert User Role
     */
    async upsertUserRoleApiV1UserRolesUsernamePutRaw(requestParameters: UpsertUserRoleApiV1UserRolesUsernamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRoleResponse>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling upsertUserRoleApiV1UserRolesUsernamePut().'
            );
        }

        if (requestParameters['userRoleUpdate'] == null) {
            throw new runtime.RequiredError(
                'userRoleUpdate',
                'Required parameter "userRoleUpdate" was null or undefined when calling upsertUserRoleApiV1UserRolesUsernamePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/user-roles/{username}`;
        urlPath = urlPath.replace(`{${"username"}}`, encodeURIComponent(String(requestParameters['username'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserRoleUpdateToJSON(requestParameters['userRoleUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRoleResponseFromJSON(jsonValue));
    }

    /**
     * Upsert User Role
     */
    async upsertUserRoleApiV1UserRolesUsernamePut(requestParameters: UpsertUserRoleApiV1UserRolesUsernamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRoleResponse> {
        const response = await this.upsertUserRoleApiV1UserRolesUsernamePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
